apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookscrud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shoebimtiaz/BooksCRUDWithASP.NETCore5'
    targetRevision: main
    path: bookscrud
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true